terms:
  - id: isCitedBy
    term: is cited by
    active: true
  - id: cites
    term: cites
    active: true
  - id: isSupplementTo
    term: is supplement to
    active: true
  - id: isSupplementedBy
    term: is supplemented by
    active: true
  - id: isContinuedBy
    term: is continued by
    active: true
  - id: continues
    term: continues
    active: true
  - id: isDescribedBy
    term: is described by
    active: true
  - id: describes
    term: describes
    active: true
  - id: hasMetadata
    term: has metadata
    active: true
  - id: isMetadataFor
    term: is metadata for
    active: true
  - id: hasVersion
    term: has version
    active: true
  - id: isVersionOf
    term: is version of
    active: true
  - id: isNewVersionOf
    term: is new version of
    active: true
  - id: isPreviousVersionOf
    term: is previous version of
    active: true
  - id: isPartOf
    term: is part of
    active: true
  - id: hasPart
    term: has part
    active: true
  - id: isPublishedIn
    term: is published in
    active: true
  - id: isReferencedBy
    term: is referenced by
    active: true
  - id: references
    term: references
    active: true
  - id: isDocumentedBy
    term: is documented by
    active: true
  - id: documents
    term: documents
    active: true
  - id: isCompiledBy
    term: is compiled by
    active: true
  - id: compiles
    term: compiles
    active: true
  - id: isVariantFormOf
    term: is variant form of
    active: true
  - id: isOriginalFormOf
    term: is original form of
    active: true
  - id: isIdenticalTo
    term: is identical to
    active: true
  - id: isReviewedBy
    term: is reviewed by
    active: true
  - id: reviews
    term: reviews
    active: true
  - id: isDerivedFrom
    term: is derived from
    active: true
  - id: isSourceOf
    term: is source of
    active: true
  - id: isCommentOn
    term: is comment on
    active: false
  - id: hasComment
    term: has comment
    active: false
  - id: isReplyTo
    term: is reply to
    active: false
  - id: hasReply
    term: has reply
    active: false
  - id: basedOnData
    term: based on data
    active: false
  - id: hasRelatedMaterial
    term: has related material
    active: false
  - id: isBasedOn
    term: is based on
    active: false
  - id: isBasisFor
    term: is basis for
    active: false
  - id: isRequiredBy
    term: is required by
    active: true
  - id: requires
    term: requires
    active: true
  - id: hasParent
    term: has parent
    active: false
  - id: isParentOf
    term: is parent of
    active: false
  - id: isObsoletedBy
    term: is obsoleted by
    active: true
  - id: Obsoletes
    term: obsoletes
    active: true
  - id: isCollectedBy
    term: is collected by
    active: true
  - id: collects
    term: collects
    active: true
