terms:
  - id: Audiovisual
    term: Audiovisual
    active: true
  - id: Book
    term: Book
    active: true
  - id: BookChapter
    term: Book Chapter
    active: true
  - id: Collection
    term: Collection
    active: true
  - id: ComputationalNotebook
    term: Computational Notebook
    active: true
  - id: ConferencePaper
    term: Conference Paper
    active: true
  - id: DataPaper
    term: Data Paper
    active: true
  - id: Dataset
    term: Dataset
    active: true
  - id: Dissertation
    term: Dissertation
    active: true
  - id: Event
    term: Event
    active: true
  - id: Image
    term: Image
    active: true
  - id: InteractiveResource
    term: Interactive Resource
    active: true
  - id: Journal
    term: Journal
    active: true
  - id: JournalArticle
    term: Journal Article
    active: true
  - id: Model
    term: Model
    active: true
  - id: OutputManagementPlan
    term: Output Management Plan
    active: true
  - id: PeerReview
    term: Peer Review
    active: true
  - id: PhysicalObject
    term: Physical Object
    active: true
  - id: Preprint
    term: Preprint
    active: true
  - id: Report
    term: Report
    active: true
  - id: Service
    term: Service
    active: true
  - id: Software
    term: Software
    active: true
  - id: Sound
    term: Sound
    active: true
  - id: Standard
    term: Standard
    active: true
  - id: Text
    term: Text
    active: true
  - id: Workflow
    term: Workflow
    active: true
  - id: Other
    term: Other
    active: true
