# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource Dataset`

attributes:
  doi:
    type: string
    multiple: false
    form:
      multiple: false
      primary: false
    index_keys:
      - "doi_ssim"
    predicate: http://purl.org/spar/datacite/doi
  tombstone_status:
    type: string
    multiple: false
    index_keys:
      - "tombstone_status_ssim"
    predicate: http://www.example.com/vocabs/demo/tombstoneStatus
  tombstone_date:
    type: string
    multiple: false
    index_keys:
      - "tombstone_date_ssim"
    predicate: http://www.example.com/vocabs/demo/tombstoneDate
  is_tombstoned:
    type: string
    index_keys:
      - "is_tombstoned_ssim"
    predicate: http://www.example.com/vocabs/demo/isTombstone
  format:
    type: string
    multiple: true
    index_keys:
      - "format_ssim"
    predicate: http://www.example.com/vocabs/demo/format
  files_size:
    type: integer
    multiple: true
    form:
      primary: false
    index_keys:
      - "files_size_tesim"
    predicate: http://www.example.com/vocabs/demo/size
  software_version:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "software_version_tesim"
    predicate: http://www.example.com/vocabs/demo/softwareVersion
  dataset_method:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "dataset_method_tesim"
    predicate: http://www.example.com/vocabs/demo/datasetMethod
  series_information:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "series_information_tesim"
    predicate: http://www.example.com/vocabs/demo/seriesInformation
  table_of_contents:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "table_of_contents_tesim"
    predicate: http://www.example.com/vocabs/demo/tableOfContents
  technical_information:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "technical_information_tesim"
    predicate: http://www.example.com/vocabs/demo/technicalInformation
